bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, J, swapwindow, d

$rc = 50 # resize coefficient

bind = $mainMod CTRL, H, resizeactive, -$rc  0
bind = $mainMod CTRL, L, resizeactive,  $rc  0
bind = $mainMod CTRL, K, resizeactive,  0   -$rc
bind = $mainMod CTRL, J, resizeactive,  0    $rc

bindm = $mainMod SHIFT, mouse:272, resizewindow

bind = $mainMod, W, fullscreen
bind = $mainMod, B, pin

bind = $mainMod, F, exec, firefox
bind = $mainMod, Z, exec, zathura

bindr = $mainMod, X, exec, pkill waybar || waybar
